const express = require("express");
const userRoute = require("./user.route");
const categoryRoute=require("./category.route");
const bookRoute=require("./book.route");
const stationaryRoute=require("./stationary.route");
const schoolRoute=require("./school.route");
const musicRoute=require("./music.route");
const movieRoute=require("./movie.route");
const hotelRoute=require("./hotel.route");
const busRoute=require("./bus.route");
const jwelleryRoute=require("./jwellery.route");
const travelRoute=require("./travel.route");
const pharmacyRoute=require("./pharmacy.route");
const groceryRoute=require("./grocery.route");
// const tokenRoute=require("./token.route");
const productRoute=require("./product.route");
const router = express.Router();

router.use("/user", userRoute);
router.use("/category", categoryRoute);
router.use("/book", bookRoute);
router.use("/stationary", stationaryRoute);
router.use("/school", schoolRoute);
router.use("/music", musicRoute);
router.use("/movie", movieRoute);
router.use("/hotel", hotelRoute);
router.use("/bus", busRoute);
router.use("/jwellery", jwelleryRoute);
router.use("/travel", travelRoute);
router.use("/pharmacy", pharmacyRoute);
router.use("/grocery", groceryRoute);
// router.use("/token", tokenRoute);
router.use("/product", productRoute);

module.exports = router;